routes/web.php
<?php

use App\Http\Controllers\WorktimeTrackerController;
use App\Models\WorktimeTracker;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [WorktimeTrackerController::class, 'overview'])->name("index");

Route::get('/worktime-trackers/export', [WorktimeTrackerController::class, 'exportCsv'])->name("export");

Route::resource('worktime-trackers', WorktimeTrackerController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/WorktimeTracker.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class WorktimeTracker extends Model
{
    use HasFactory;

    protected $with = ['user'];

    protected $appends = ['hours'];

    protected $dates = ['date'];

    protected $guarded = [];

    /**
     * @return BelongsTo
     */
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'user_id')->select("id", "name");
    }

    public function getHoursAttribute(): float|int
    {
        $firstTime=strtotime($this->s_time);
        $lastTime=strtotime($this->e_time);
        $timeDiff= $lastTime - $firstTime;
        return $timeDiff/3600;
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/WorktimeTrackerController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreWorktimeTrackerRequest;
use App\Http\Requests\UpdateWorktimeTrackerRequest;
use App\Models\WorktimeTracker;
use Carbon\Carbon;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\StreamedResponse;

class WorktimeTrackerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function index(): View
    {
        $trackers = WorktimeTracker::latest()->paginate(5);

        return view('worktime-tracker.index', compact('trackers'));
    }

    public function overview(): View
    {
        $trackers = WorktimeTracker::all();

        $monthly = $trackers
            ->groupBy(function (WorktimeTracker $item) {
                return $item->date->format('Y-m');
            })->map(function($rows) {
                return [
                    'hours' => $rows->sum('hours'),
                ];
            });

        $weekly = $trackers
            ->groupBy(function($item) {
                $created_at = Carbon::parse($item->date);
                $start = $created_at->startOfWeek()->format('d-m-Y');
                $end = $created_at->endOfWeek()->format('d-m-Y');

                return "{$start} - {$end}";
            })
            ->map(function($rows) {
                return [
                    'hours' => $rows->sum('hours'),
                ];
            });

        $daily = $trackers
            ->groupBy(function (WorktimeTracker $item) {
                return $item->date->format('Y-m-d');
            })->map(function($rows) {
                return [
                    'hours' => $rows->sum('hours'),
                ];
            });

        return view('worktime-tracker.overview', compact('monthly', 'weekly', 'daily'));
    }

    /**
     * @return View
     */
    public function create(): View
    {
        return view('worktime-tracker.create');
    }

    /**
     * @param StoreWorktimeTrackerRequest $request
     * @return RedirectResponse
     */
    public function store(StoreWorktimeTrackerRequest $request): RedirectResponse
    {
        $date = $request->input("date");
        $worktimeTracker = new WorktimeTracker([
            'body' => $request->input("body"),
            'date' => $date,
            'user_id' => 1,
            "s_time" => $request->input("s-time"),
            "e_time" => $request->input("e-time"),
        ]);
        $worktimeTracker->save();

        return redirect()->route('worktime-trackers.index')->with('success', 'Entry created successfully.');
    }

    /**
     * @param WorktimeTracker $worktimeTracker
     * @return View
     */
    public function edit(WorktimeTracker $worktimeTracker): View
    {
        $tracker = $worktimeTracker;
        return view('worktime-tracker.edit', compact('tracker'));
    }

    /**
     * @param UpdateWorktimeTrackerRequest $request
     * @param WorktimeTracker $worktimeTracker
     * @return RedirectResponse
     */
    public function update(UpdateWorktimeTrackerRequest $request, WorktimeTracker $worktimeTracker): RedirectResponse
    {
        $date = $request->input("date");
        $worktimeTracker->update([
            'body' => $request->input("body", $worktimeTracker->body),
            'date' => $date,
            'user_id' => 1,
            "s_time" => $request->input("s-time"),
            "e_time" => $request->input("e-time"),
        ]);

        $worktimeTracker->refresh();
        return redirect()->route('worktime-trackers.index')
            ->with('success', 'Entry updated successfully');
    }

    /**
     * @param WorktimeTracker $worktimeTracker
     * @return RedirectResponse
     */
    public function destroy(WorktimeTracker $worktimeTracker): RedirectResponse
    {
        $worktimeTracker->delete();

        return redirect()->route('worktime-trackers.index')
            ->with('success', 'Entry deleted successfully');
    }

    /**
     * @param Request $request
     * @return StreamedResponse
     */
    public function exportCsv(Request $request): StreamedResponse
    {
        $fileName = 'worktime-tracker.csv';
        $trackers = WorktimeTracker::all();

        $headers = array(
            "Content-type"        => "text/csv",
            "Content-Disposition" => "attachment; filename=$fileName",
            "Pragma"              => "no-cache",
            "Cache-Control"       => "must-revalidate, post-check=0, pre-check=0",
            "Expires"             => "0"
        );

        $columns = array('Description', 'Date', 'Start Time', 'End Time', 'Hours');

        $callback = function() use($trackers, $columns) {
            $file = fopen('php://output', 'w');
            fputcsv($file, $columns);

            foreach ($trackers as $tracker) {
                $row['Description']  = $tracker->body;
                $row['Date']    = $tracker->date;
                $row['Start Time']    = $tracker->s_time;
                $row['End Time']  = $tracker->e_time;
                $row['Hours']  = $tracker->hours;

                fputcsv($file, array($row['Description'], $row['Date'], $row['Start Time'], $row['End Time'], $row['Hours']));
            }

            fclose($file);
        };

        return response()->stream($callback, 200, $headers);
    }
}

resources/views/layouts/app.blade.php
<html>

<head>
    <title>Worktime Tracker - @yield('title')</title>

    <!-- Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js"
            integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous">
    </script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js"integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous">
    </script>

    <style>
     .footer {
      position: fixed;
      left: 0;
      bottom: 0;
      width: 100%;
      background-color: #9C27B0;
      color: white;
      text-align: center;
     }

    </style>

</head>

<body>
@section('sidebar')

@show

<div class="container">
    @yield('content')
</div>
<div class="text-center footer">
    <h4>WORKTIME TRACKER</h4>
</div>
</body>

</html>

resources/views/worktime-tracker/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Add New Entry</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('worktime-trackers.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <form action="{{ route('worktime-trackers.store') }}" method="POST" >
        @csrf

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <input type="text" class="form-control" name="body" placeholder="Description">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Date:</strong>
                    <input type="date" name="date" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Start time:</strong>
                    <input type="time" name="s-time" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>End time:</strong>
                    <input type="time" name="e-time" class="form-control">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/worktime-tracker/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Entry</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('worktime-trackers.index') }}" title="Go back"> <i class="fas fa-backward "></i> </a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('worktime-trackers.update', $tracker->id) }}" method="POST">
        @csrf
        @method('PUT')

        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Description:</strong>
                    <input class="form-control" type="text" name="body" value="{{ $tracker->body }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Date:</strong>
                    <input type="date" name="date" class="form-control" value="{{ $tracker->date->format('Y-m-d') }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Start time:</strong>
                    <input type="time" name="s-time" class="form-control" value="{{ $tracker->s_time }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>End time:</strong>
                    <input type="time" name="e-time" class="form-control" value="{{ $tracker->e_time }}">
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>

    </form>
@endsection

resources/views/worktime-tracker/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <a class="btn btn-success" href="{{ route('index') }}" title="Go to index"> <i class="far fa-business-time"></i>
                    Overview
                </a>
                <h2>Worktime Tracker </h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('worktime-trackers.create') }}" title="Create a entry"> <i class="fas fa-plus-circle"></i>
                </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <a class="btn btn-success" href="{{ route('export') }}" title="Export"> <i class="far fa-business-time"></i>
        Export as CSV
    </a>
    <table class="table table-bordered table-responsive-lg">
        <tr>
            <th>ID</th>
            <th>Body</th>
            <th>User Name</th>
            <th>Date</th>
            <th>Start Time</th>
            <th>End Time</th>
            <th>Hours</th>
            <th>Date Created</th>
            <th>Action</th>
        </tr>
        @foreach ($trackers as $tracker)
            <tr>
                <td>{{ $tracker->id }}</td>
                <td>{{ $tracker->body }}</td>
                <td>{{ $tracker->user->name }}</td>
                <td>{{ $tracker->date->format('Y-m-d') }}</td>
                <td>{{ $tracker->s_time }}</td>
                <td>{{ $tracker->e_time }}</td>
                <td>{{ $tracker->hours }}</td>
                <td>{{ date_format($tracker->created_at, 'jS M Y') }}</td>
                <td>
                    <form action="{{ route('worktime-trackers.destroy', $tracker->id) }}" method="POST">
                        <a href="{{ route('worktime-trackers.edit', $tracker->id) }}">
                            <i class="fas fa-edit  fa-lg"></i>
                        </a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" title="delete" style="border: none; background-color:transparent;">
                            <i class="fas fa-trash fa-lg text-danger"></i>
                        </button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>

    {!! $trackers->links() !!}

@endsection

resources/views/worktime-tracker/overview.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Worktime Tracker - OVERVIEW</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('worktime-trackers.index') }}" title="Go to index"> <i class="far fa-business-time"></i>
                    Entries
                </a>
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <div class="row">
        <div class="col-xs-12 col-sm-4 col-md-4">
            <h1>Monthly</h1>
            <table class="table table-bordered table-responsive-lg">
                <tr>
                    <th>Month</th>
                    <th>Hours</th>
                </tr>
                @foreach ($monthly as $key => $item)
                    <tr>
                        <td>{{ $key }}</td>
                        <td>{{ $item['hours'] }}</td>
                    </tr>
                @endforeach
            </table>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
            <h1>Weekly</h1>
            <table class="table table-bordered table-responsive-lg">
                <tr>
                    <th>Week</th>
                    <th>Hours</th>
                </tr>
                @foreach ($weekly as $key => $item)
                    <tr>
                        <td>{{ $key }}</td>
                        <td>{{ $item['hours'] }}</td>
                    </tr>
                @endforeach
            </table>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4">
            <h1>Daily</h1>
            <table class="table table-bordered table-responsive-lg">
                <tr>
                    <th>Day</th>
                    <th>Hours</th>
                </tr>
                @foreach ($daily as $key => $item)
                    <tr>
                        <td>{{ $key }}</td>
                        <td>{{ $item['hours'] }}</td>
                    </tr>
                @endforeach
            </table>
        </div>
    </div>

@endsection